### ISSUE TITLE
Add Gallery of Customer Prints

### ISSUE THREAD

**Issue by arroyoDev** [ArroyoDev-LLC/Big3D#11]
This needs a gallery section.   

when you start this, lets discuss 2 options..   
 1.  just use the gallery control.. and how we get new images added 
2.  just connect to an instagram account for image management.   

![image.png](https://images.zenhubusercontent.com/608656e80afb7ef00c79f176/22bcdd3f-f75f-482f-9369-45d44c70e59b)

**Comment by pablo014** [comment]
@arroyoDev community section
https://github.com/ArroyoDev-LLC/Big3D/pull/17
